// Original Chinese achievement titles and descriptions; IDs are save-compatible.
export const ACHIEVEMENT_NAMES: Record<string,string> = {
  "humble": "微末之始",
  "levelup": "脑洞大开",
  "departure": "开枝散叶",
  "evolution_1": "进化的号角 I",
  "evolution_2": "进化的号角 II",
  "evolution_3": "进化的号角 III",
  "evolution_4": "进化的号角 IV",
  "evolution_5": "进化的号角 V",
  "evolution_6": "进化的号角 VI",
  "millionaire": "百万粮仓",
  "billionaire": "巨龙囤积症",
  "strength": "虫多势众",
  "treat_1": "无上珍馐 I",
  "treat_2": "无上珍馐 II",
  "treat_3": "无上珍馐 III",
  "treat_4": "无上珍馐 IV",
  "treat_5": "无上珍馐 V",
  "build_foragers": "遍地野果",
  "build_haulers": "昂首阔步",
  "build_gemini": "步阔首昂",
  "build_brain": "智慧大脑",
  "build_farm": "甘甜乳汁",
  "build_orchard": "落地生根",
  "build_throwers": "使命必达",
  "build_traps": "虫肉大餐",
  "build_cuisine": "饕餮盛宴",
  "build_mushies": "林间漫步",
  "build_fish": "扬帆起航",
  "build_tunnels": "空间魔术",
  "build_mine": "地下狂热",
  "aphid_type": "热辣鲜奶",
  "golden_tree": "奇迹降临",
  "golden_bush": "奇妙魔法",
  "omelette": "芝士煎蛋卷",
  "cordon": "地狱厨房",
  "spore_100": "快乐蘑菇",
  "spore_150": "完美共生",
  "bait_fish": "愿者上钩",
  "bait_bug": "诱敌深入",
  "30_foragers": "嗡嗡作响",
  "30_haulers": "大排长龙",
  "30_throwers": "多相睡眠",
  "30_trappers": "狩猎解禁",
  "30_mushies": "科学万岁",
  "2_tunnellers": "掘地虫",
  "5_boats": "乘风破浪",
  "squish": "爆浆时刻",
  "thrower_ms": "群魔乱舞",
  "thrower_ts": "疾速连发",
  "hauler_ms": "闪电跑酷",
  "hauler_tr": "虫力投石机",
  "max_bushes": "超级繁花",
  "ballon": "金球奖",
  "balanced": "应有尽有",
  "shiny_fear": "烟花璀璨",
  "max_trap": "天罗地网",
  "max_trees": "绿意盎然",
  "max_cold": "冰川时代",
  "max_hot": "尽情燃烧",
  "max_frostburn": "慢火熬煮",
  "max_sour": "酸甜交织",
  "max_ecsta": "赞美太阳",
  "max_irid": "意乱情迷",
  "max_umami": "第五元素",
  "max_bonus": "完美调味",
  "max_mult": "究极香料配方",
  "max_feast": "满载而归",
  "3_buffs": "美食家",
  "no_carrier": "大道至简",
  "lean": "井然有序",
  "diamond": "蒙尘明珠",
  "pet": "最佳萌宠",
  "overflow": "产能溢出",
  "manual": "亲力亲为",
  "tricks": "空中飞人",
  "destiny": "祖传家业",
  "rebirthed": "逆向进化",
  "nevermind": "出师不利",
  "overmind": "基因飞升"
};
export const ACHIEVEMENT_DESCRIPTIONS: Record<string,string> = {
  "humble": "给蚁后扔颗浆果。",
  "levelup": "升级蚁后。",
  "departure": "孵化公主，开启全新篇章。",
  "evolution_1": "获得首个基因点数，解锁第1级基因升级。",
  "evolution_2": "解锁第2级基因升级。",
  "evolution_3": "解锁第3级基因升级。",
  "evolution_4": "解锁第4级基因升级。",
  "evolution_5": "解锁第5级基因升级。",
  "evolution_6": "解锁最高级基因升级。",
  "millionaire": "食物储备达到100万份。",
  "billionaire": "囤积10亿份食物。",
  "strength": "孵化100只幼虫。",
  "treat_1": "吃下价值大于100点的食物。",
  "treat_2": "吃下价值大于1000点的食物。",
  "treat_3": "吃下价值大于1万点的食物。",
  "treat_4": "吃下价值大于10万点的食物。",
  "treat_5": "吃下价值大于100万点的食物。",
  "build_foragers": "建造觅食者地洞。",
  "build_haulers": "建造搬运工巢房。",
  "build_gemini": "建造另一座巢房。",
  "build_brain": "建造进化腔。",
  "build_farm": "建造农场。",
  "build_orchard": "建造果园。",
  "build_throwers": "建造投掷者洞窟。",
  "build_traps": "建造陷阱工坊。",
  "build_cuisine": "建造厨房。",
  "build_mushies": "建造蘑菇实验室。",
  "build_fish": "建造渔场。",
  "build_tunnels": "建造隧道网络。",
  "build_mine": "建造矿场。",
  "aphid_type": "解锁新种类的蚜虫。",
  "golden_tree": "在果园中种出金苹果。",
  "golden_bush": "在果丛中发现金苹果。",
  "omelette": "在厨房中烹饪一道菜肴。",
  "cordon": "在厨房中同时烹饪2道不同的菜肴。",
  "spore_100": "孢子效率达到100%。",
  "spore_150": "孢子效率达到150%。",
  "bait_fish": "成功钓到鱼。",
  "bait_bug": "成功诱捕虫子。",
  "30_foragers": "孵化30名觅食者。",
  "30_haulers": "孵化30名搬运工。",
  "30_throwers": "孵化30名投掷者。",
  "30_trappers": "孵化30名陷阱猎手。",
  "30_mushies": "孵化30名真菌学家。",
  "2_tunnellers": "孵化多名掘地工。",
  "5_boats": "建造5艘渔船。",
  "squish": "单次挤奶让蚜虫产出20份食物。",
  "thrower_ms": "投掷者的移动速度达到300点。",
  "thrower_ts": "投掷者的投掷速度达到250%。",
  "hauler_ms": "搬运工的移动速度达到1000点。",
  "hauler_tr": "搬运工的投掷距离达到1000%。",
  "max_bushes": "一次性发现11丛果丛。",
  "ballon": "利用投掷者的脑袋将苹果变成金色的。",
  "balanced": "蚁后的饮食中包含6种不同的食物。",
  "shiny_fear": "惊吓一只闪光蚜虫。",
  "max_trap": "从单个陷阱中获取75份肉丸。",
  "max_trees": "在果园的单个周期内种出80颗果实。",
  "max_cold": "严寒达到100层。",
  "max_hot": "酷热达到5000层。",
  "max_frostburn": "霜燃达到1000层。",
  "max_sour": "酸涩达到500层。",
  "max_ecsta": "迷醉达到100层。",
  "max_irid": "虹彩达到50层。",
  "max_umami": "鲜味达到200层。",
  "max_bonus": "加成达到3000点。",
  "max_mult": "倍率达到100倍。",
  "max_feast": "将菜肴用作诱饵，使单次捕鱼作业达到最高效率。",
  "3_buffs": "同时激活3种不同的增益效果。",
  "no_carrier": "在不孵化任何觅食者、搬运工或投掷者的情况下，食物产量达到每分钟100万份。",
  "lean": "购买“产下幼虫”不超过10次，且食物产量达到每分钟1000万份。",
  "diamond": "在不建造矿场的情况下，食物产量达到每分钟10亿份。",
  "pet": "抚摸蚜虫。",
  "overflow": "设施的储备量超出其最大上限。",
  "manual": "亲手扔出一百颗浆果。辛苦了！快去休息吧。",
  "tricks": "连续表演3次杂技。",
  "destiny": "继承1亿份食物。",
  "rebirthed": "将劳工退化为幼虫。",
  "nevermind": "在建立新群落后的10分钟内再次建立新群落。",
  "overmind": "获得第25个基因点数。"
};
